### ISSUE TITLE
1Password 6.5 update breaks `hyperterm-1password`

### ISSUE THREAD

**Issue by olivier-w** [sibartlett/hyperterm-1password#3]
<img width="493" alt="screen shot 2016-11-28 at 1 41 54 pm" src="https://cloud.githubusercontent.com/assets/465250/20681189/71fdd96c-b570-11e6-9a1d-6a241b5008a7.png">

Using:
1Password Version 6.5.2 (652002) [Mac App Store]
Hyper.app Version 0.8.3 (0.8.3.873)

Looks to be the same issue that's been documented here: https://github.com/ravenac95/sudolikeaboss/issues/29

**Comment by sibartlett** [comment]
Thanks for reporting this issue, I am already working on a solution.

**Comment by sibartlett** [comment]
I just published an update that should solve this issue.

**Comment by olivier-w** [comment]
@sibartlett Thank you! Works beautifully again 🎉
