### ISSUE TITLE
always asking to update the 1password extension

### ISSUE THREAD

**Issue by opensourceportfolio** [sibartlett/hyperterm-1password#7]
Hi, each time I trigger the extension, I keep getting a pop up asking me to update the extension. If I click "update now" the popup disappears but nothing else happens. Have I misconfigured the extension?

Thanks

**Comment by sibartlett** [comment]
You need to update the plugins from within Hyper.

> Hyper menubar > Plugins > Update All Now

**Comment by opensourceportfolio** [comment]
Hi @sibartlett 

Thanks for the reply but I've done this many times. It is still happening however.

**Comment by opensourceportfolio** [comment]
I have just removed and then readded the plugin and everything is back to normal. Thanks again @sibartlett

**Comment by sibartlett** [comment]
Hmmm, that's weird. Maybe it wasn't updating properly or something.
